### ISSUE TITLE
IP Limit

### ISSUE THREAD

**Issue by yishais** [stellar-expert/operations-notifier#16]
If i'm correct, the notifier will open a "general" stream against Horizon and will filter it based on the account list in the DB vs. opening individual streams agains each account. (is that right?). In this case, Horizon counts every payment update in the stream as a request (?). Currently the Horizon request limit is 3,600 per hour. I read somewhere it is 17,200 on the steller.org horizon. 

I keep hitting the Rate Limit error more than I want. In the past four hours, I've been getting it every 30 seconds (and it looks like the current rate is ~70K payment per hour).

Is it a notifier setting? Am I using the notifier correctly? Did you see this issues before?

Status: 429, message: Too Many Requests, horizon: stellar-main.bdnodes.net

Thanks

-Yishai

**Comment by orbitlens** [comment]
> If i'm correct, the notifier will open a "general" stream against Horizon and will filter it based on the account list in the DB vs. opening individual streams agains each account (is that right?)

Yes, it's the main idea behind the service. 

> I keep hitting the Rate Limit error more than I want. 

No, we didn't have such problems in the past. Currently we are using slightly different approach for our ingestion engine – streaming ledgers and then fetching all coresponding transactions when new ledger arrives. In this way, fetching all ledger transactions costs at most 6 rate limiting credits (1 credit for the streamed ledger, and max 5 credits for fetching transactions - 200 transactions in a batch).

I'll port the new logic into this repository tomorrow.

Thanks for reporting the rate limiting issue, @yishais.

**Comment by orbitlens** [comment]
@yishais 
I merged changes that should address your issue and updated StellarSDK to the latest version.

Please let me know if you face any other problems with rate limiting.
